# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: set ssh env
        run: |
          ls
          mkdir -p ~/.ssh
          echo "${{ secrets.KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          git clone git@github.com:cagiant/configs.git
          cp ./configs/coc-data/application.properties ./src/main/resources/
          rm -rf configs
      
      # Runs a single command using the runners shell
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      
      - name: scp file to txyun
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "./target/data-0.0.1-SNAPSHOT.jar"
          target: "/home/ubuntu/projects/coc"

      - name: run publish script
        uses: fifsky/ssh-action@master
        with:
          command: |
            java -jar /home/ubuntu/projects/coc/data-0.0.1-SNAPSHOT.jar
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
         
